## Assignment

We will use the Ames Housing dataset for the assignment.

```{r}
library(tidyverse)
ames <- read.csv('train.csv')
options(scipen = 999)
```

```{r}
glimpse(ames)
```

Gain & visualize 4 insights from the Ames housing dataset

1. Count of one categorical feature
```{r}
#Missing Value Distribution
missing <- data.frame(t(colSums(is.na(ames))))
missing[missing == 0] <- NA
missing <- missing[ , colSums(is.na(missing)) == 0]

counts <- as.numeric(missing[1,])
vars <- colnames(missing)
df <- data.frame(counts, vars)

df %>% ggplot(aes(x=reorder(vars,counts), y=counts)) + 
  geom_bar (stat = 'identity', alpha = 0.6, fill = 'Red') +
  coord_flip() +
  geom_text(aes(label = counts), nudge_y = 50) +
  theme_minimal() +
  labs(title = 'Distribution of Missing Values from Ames Dataset',
       subtitle = 'Some missing values are equals across variables since they are related',
       caption = 'Dataset contains missing values from some variable',
       x = 'Variables',
       y = 'Missing Values Counts') 
  
```

```{r}
#Distribution of Overall Quality of Houses
ames$OverallQual <- as.factor(ames$OverallQual)

ames %>%
  count(OverallQual) %>%
  ggplot(aes(x = OverallQual, y = n, fill = OverallQual)) +
  scale_fill_brewer(palette="Paired") +
  geom_bar(stat = 'identity', alpha = 0.6) +
  geom_text(aes(label = n ),nudge_y = 15) +
  theme_minimal() +
  labs(title = 'Distribution of Overall Quality of Houses from Ames Dataset',
       subtitle = 'Most Houses in sale had an Overall Quality of 5,6,and 7',
       caption = 'There are around 300-ish houses for each Quality Rating of 5,6, and 7',
       x = 'Overall Quality',
       y = 'Counts')

```

2. Distribution of one continuous feature
```{r}
#Sale Price Distribution
ames %>% ggplot(aes(x= SalePrice)) + 
  geom_histogram(aes(y=..density..), alpha = 0.5) +
  geom_density(col = 'red') +
  theme_minimal() +
  labs(title = 'Distribution of Sale Price Variable from Ames Dataset',
       subtitle = 'Distribution shows Peak, Positive Skewness',
       caption = 'Data should be scaled and transformed to fix the skew',
       x = 'Sale Price',
       y = 'Frequency')
```

3. Categorical-continuous
```{r}
#Sale Price in relation to OverAll Quality
ames %>% ggplot(aes(x= OverallQual, y=SalePrice)) +
  geom_boxplot(alpha=0.2, fill = 'blue') +
  theme(legend.position="none") +
  theme_minimal() +
  stat_summary(fun = median,
               geom = "line",
               aes(group = 1),
               col = "red") +
  labs(title = 'Sale Price and Overall Quality Relationship from Ames Dataset',
       subtitle = 'Sale Price relatively increases as Overall Quality of Houses Increases',
       caption = 'There is a positive Correlation',
       x = 'Overall Quality',
       y = 'Sale Price')
```


4. Continuous-continuous
```{r}
#Sale Price in relation to Living Area
ames %>% ggplot(aes(x= GrLivArea, y= SalePrice)) +
  geom_point(alpha = 0.3) +
  geom_smooth(method=lm,  linetype="dashed",
             color="darkred", fill="blue") +
  theme_minimal() +
  labs(title = 'Sale Price and Living Area Relationship from Ames Dataset',
       subtitle = 'Sale Price relatively increases as Living Area of Houses Increases',
       caption = 'There is a positive Correlation',
       x = 'Sale Price',
       y = 'Frequency')
```